---
- name: Ensure services are down
  delegate_to: localhost
  ansible.builtin.command:
    cmd: '{{ docker_command }} down'
    chdir: '{{ [playbook_dir, local_docker_directory] | path_join }}'

- name: Set facts
  ansible.builtin.set_fact:
    synchronized_data_dirs: "{{ data_dirs | dict2items | selectattr('value.pull') }}"
    precreated_data_dirs: "{{ data_dirs | dict2items | rejectattr('value.pull') }}"

- name: Synchronize local docker data directories
  delegate_to: localhost
  become: yes
  ansible.builtin.synchronize:
    src: "{{ [playbook_dir, 'data', item.value.path | basename] | path_join }}"
    dest: '{{ [playbook_dir, local_docker_directory] | path_join }}'
    delete: true
  loop: "{{ synchronized_data_dirs }}"

- name: Ensure correct ownership of docker data directories
  delegate_to: localhost
  become: yes
  ansible.builtin.file:
    path: '{{ [playbook_dir, local_docker_directory, item.value.path | basename] | path_join }}'
    owner: '{{ item.value.owner | default(omit) }}'
    group: '{{ item.value.group | default(omit) }}'
    recurse: yes
  loop: "{{ synchronized_data_dirs }}"

- name: Ensure local data directies that have not been pulled
  delegate_to: localhost
  become: yes
  ansible.builtin.file:
    state: directory
    path: '{{ [playbook_dir, local_docker_directory, item.value.path | basename] | path_join }}'
    owner: '{{ item.value.owner | default(omit) }}'
    group: '{{ item.value.group | default(omit) }}'
    mode: "{{ item.value.mode | default('0750') }}"
  loop:  "{{ precreated_data_dirs }}"
  when: item.value.local | default(true)

#  TODO: Perhaps should instead check which services where runing before and start only those
# also, perhaps this probably not be done here as an unexpected side effect, but leaving for now
- name: Ensure services are up
  delegate_to: localhost
  ansible.builtin.command:
    cmd: '{{ docker_command }} up -d'
    chdir: '{{ [playbook_dir, local_docker_directory] | path_join }}'
